### ISSUE TITLE
Is it possible to use this to redirect all www traffic to non-www url?

### ISSUE THREAD

**Issue by SKeeneCode** [cusspvz/redirect.docker#11]
As title. Bit of a newbie on all this, thanks :) Looking to redirect all traffic going to www.MYURL.com/* to MYURL.com/*

**Comment by ThomDietrich** [comment]
That's not what this project is for. URLs are linked in your webserver or proxy. Use this project to then serve https on `MYURL.com`, `www.MYURL.com`, `whatever.MYURL.com`

I would not implement this feature here as domain assignment and resolution can become a lot more complex than you might think.

Look into typical reverse proxy tutorials (solution depends on your skills level):

- https://www.freecodecamp.org/news/docker-nginx-letsencrypt-easy-secure-reverse-proxy-40165ba3aee2/
- https://www.digitalocean.com/community/tutorials/how-to-use-traefik-as-a-reverse-proxy-for-docker-containers-on-ubuntu-18-04

**Comment by cusspvz** [comment]
> As title. Bit of a newbie on all this, thanks :) Looking to redirect all traffic going to [www.MYURL.com/](http://www.MYURL.com/)* to MYURL.com/*

Yes you can. The main purpose of this project is to have a web service which only responsibility is to respond to http requests with a 301/302 status codes.

Although, as @ThomDietrich said, it won't specifically handle Host resolution and you'll need to have a different service handling the routing (such a Load Balancer).

In case you already have a LB, you can spin up this service redirecting to `MYURL.com/*` and have traffic that goes to the `www.MYURL.com` land in it.

Going to close this issue. If you have any notes regarding this, please ask for a reopening
