### ISSUE TITLE
nginx: [emerg] open() "/run/nginx/nginx.pid" failed (2: No such file or directory)

### ISSUE THREAD

**Issue by krknopp** [cusspvz/redirect.docker#2]
The last commit caused this error to show up in all of my containers that were running this image.  I'm trying to figure out why, but figured I'd post in case you could find the solution faster.

**Comment by cusspvz** [comment]
Sorry, gonna see what went wrong. Thanks for noticing it.

**Comment by cusspvz** [comment]
Please, while this isn't solved, use the tag `cusspvz/redirect:0.0.1`.

**Comment by krknopp** [comment]
Great!  thanks.

**Comment by cusspvz** [comment]
Solved! You can use back the tag `0.0.2`.
Once again, thanks for noticing. For future-proof I advise you to use release tags instead of `latest` on production.

Cheers.
